name = 'sw-coupons'
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
DYNAMODB_TABLE_NAME = "summoners-war-coupons"
CUSTOM_AWS_REGION = "us-east-2"

# Set these as secrets via: wrangler secret put VARIABLE_NAME
# CUSTOM_AWS_ACCESS_KEY_ID
# CUSTOM_AWS_SECRET_ACCESS_KEY  
# HIVE_ID